from __future__ import annotations
from dataclasses import dataclass
from typing import Any

@dataclass
class Anomaly:
    """A detected statistical anomaly."""
    detector_type: str # 'zscore' or 'isolation_forest'
    date: str
    metric_name: str
    dimension_name: str | None
    dimension_value: str | None
    
    # Statistical data
    actual_value: float
    expected_value: float | None
    severity: float # The Z-score magnitude or IsolationForest score
    
    # Text generated by the LLM
    explanation: str | None = None
    
    # The chart data payload to render the anomaly
    chart_payload: dict[str, Any] | None = None
