from __future__ import annotations
from dataclasses import dataclass, field
from typing import Any

@dataclass
class InsightCandidate:
    """A generated insight candidate before ranking and LLM phrasing."""
    insight_type: str  # e.g., "wow_growth", "top_category"
    metric_name: str
    dimension_name: str | None
    
    # Statistical facts for the LLM to use
    primary_value: float | str
    comparison_value: float | str | None = None
    percent_change: float | None = None
    
    # Derived score
    score: int = 0
    
    # Text generated by the LLM
    text: str | None = None
    
    # The chart data payload to render the mini sparkline
    chart_payload: dict[str, Any] | None = None
